### ISSUE TITLE
Running on default SD models

### ISSUE THREAD

**Issue by George0726** [Attention-Refocusing/attention-refocusing#3]
Hi author,

Thanks for your impressive work! I want to run the model default SD 1.5 checkpoint. I have blocked the Gated Attention part to transfer back SD default models. It seems like there is no difference between **standard** loss and **SAR_CAR** loss. Could you mind releasing the codes for refocusing codes on default SD models?

**Comment by spurs30** [comment]
Can the proposed architecture be utilized on text-to-image models rather than grounded text-to-image such as stable diffusion? How does stable diffusion handle layout images as input.

**Comment by Attention-Refocusing** [comment]
Hi, thank for your interest. In terms of your question :"It seems like there is no difference between standard loss and SAR_CAR loss", If you want to make it work in SD, you should increase the weight of CAR, SAR loss . you can set [loss_scale](https://github.com/Attention-Refocusing/attention-refocusing/blob/ce0439cd52f0f7b78da406672244fdd1c2489f03/ldm/models/diffusion/plms.py#L121) to be 40
