### ISSUE TITLE
Cannot reproduce the result

### ISSUE THREAD

**Issue by momopusheen** [Attention-Refocusing/attention-refocusing#5]
Hi, thanks for your interesting work and well-established codebase, and I have a try. However, I have problems when reproducing the result.

- According to the paper, the method 'Layout-guidance' (arXiv:2304.03373) achieve accuracy of 12.38% and 15.56% (w/o & w/ CAR amd SAR) on **'size'** category of HRS Benchmark . 
- However, I utilized Layout-Guidance without CAR & SAR, generated images with the boxes from **'size.p'** and follow the evaluation instructions in your respository to get the accuracy. 
- I got an accuracy of 7.1856% on the **'size'** category, which is much lower than the preformance reported in the paper.
- I found that 'size.p' should have 501 prompts (as well as in **'size_compositions_prompts.csv'**), but it has only 423 prompts acctually. I think this may lead to the degration of results in evaluation.
- Other annotations also has fewer prompts than ground-truth csv.

I wonder that if you could release the inference code of 'Layout-Guidance' so I can figure out the problem.😊

Here are some links might help:
1. Layout-Guidance: _http://arxiv.org/abs/2304.03373_
2. 'size.p': _https://github.com/Attention-Refocusing/attention-refocusing/blob/main/data_evaluate_LLM/gpt_generated_box/size.p_
3. csv that serves as GT: _https://github.com/Attention-Refocusing/attention-refocusing/blob/main/data_evaluate_LLM/HRS/size_compositions_prompts.csv_

**Comment by qqphung** [comment]
Hi, the problems "I found that 'size.p' should have 501 prompts (as well as in 'size_compositions_prompts.csv'), but it has only 423 prompts acctually", because there are some repeated prompts in HRS, and I save box as dictionary of prompts, so the number of boxes will be lesser than the number of prompts in HRS

**Comment by AshkanTaghipour** [comment]
Thank you for the code and the generated images you provided. I'm encountering an issue with reproducing results for the color category based on the images outputted by your method, available [here](https://drive.google.com/file/d/1hTzrYCMFlZkfSEInPg3mXiIiJLxCjIpd/view?usp=drive_link).

Attached are the results obtained using your code and the provided images. Could you please clarify how you reported the figure of 26.32% in your paper? I double-checked the number of prompts in size.p, and it amounts to 501, which matches the number of GT prompt
![image](https://github.com/Attention-Refocusing/attention-refocusing/assets/75080077/a7025f31-85fe-43ba-870c-3e41a58e52af)

**Comment by Attention-Refocusing** [comment]
@AshkanTaghipour thanks for interesting in our work. We have just updated paper and code. We changed the hyperparameters for  better image quality. The images results is from older version, so it not match with new paper. You can run new code to reproduce the result.
