### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by git-bia19** [Attention-Refocusing/attention-refocusing#6]
!source venv/bin/activate; python guide_gligen.py --ckpt /content/gdrive/MyDrive/gligen/attention-refocusing/d_pyt.bin --file_save /content/gdrive/MyDrive/gligen/attention-refocusing/generated_imgs  --type counting --box_pickle /content/gdrive/MyDrive/gligen/attention-refocusing/data_evaluate_LLM/gpt_generated_box/counting.p
![image](https://github.com/Attention-Refocusing/attention-refocusing/assets/56919489/4deccc9f-a8bb-4f5f-8ff9-614c698bb7b3)

**Comment by Attention-Refocusing** [comment]
I believe that there are something wrong with GLIGEN model, you should check model weight, is it completely downloaded ?
